name: Docker Build All Services

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main
  schedule:
      - cron:  '0 0 * * 1'

jobs:
  build-Chemistry-Web-Service:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd ChemicalStructureWebService && docker build .
  build-Resolver:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd MetabolomicsSpectrumResolver && docker build .
  build-ExternalProxy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd GNPS_ExternalStructureProxy && docker build .
  build-FBMNComparison:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd GNPS_FBMNGroupsComparison && docker build .
  build-MASST:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd GNPS_MASST && docker build .
  build-URLFormatter:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd GNPS_URLWorkflowFormatter && docker build .

  build-Dashboard:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd GNPS_LCMSDashboard && docker build .

  build-NPClassifier:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd NP-Classifier && docker build .

  build-FlaskTemplate:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd Flask_Website_Basic_Template && docker build .

  build-StreamlitTemplate:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd Template_Streamlit_App && docker build .

  build-quickstart:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd GNPS_quickstart
        docker build -f Dockerfile.beat .
        docker build -f Dockerfile.conversion .
        docker build -f Dockerfile.website .

  build-cytoscape:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd GNPS_CytoscapeFormatting/code
        docker build -f Dockerfile .
    