name: Docker Build All Services

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main
  schedule:
      - cron:  '0 0 * * 1'

jobs:
  build-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build Chemistry Web Service
      run: |
        cd ChemistryStructureWebService && docker build .