name: Docker Build All Services

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main
  schedule:
      - cron:  '0 0 * * 1'

jobs:
  build-Chemistry-Web-Service:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd ChemicalStructureWebService && docker build .
  build-Resolver:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd MetabolomicsSpectrumResolver && docker build .
  build-ExternalProxy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd GNPS_ExternalStructureProxy && docker build .
  build-FBMNComparison:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd GNPS_FBMNGroupsComparison && docker build .
  build-MASST:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd GNPS_MASST && docker build .
  build-URLFormatter:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd GNPS_URLWorkflowFormatter && docker build .

  build-Dashboard:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Cleanup
      run: |
        docker system prune -f
    - name: Docker Build
      run: |
        cd GNPS_LCMSDashboard && docker build .